First iteration
NotUrBruddah/go-final-project pull request #1
Opened 2024-12-01 20:53 UTC by NotUrBruddah

2024-12-02 16:48 UTC, dirtymew requested changes
Привет Андрей

хорошая работа - тесты проходят

дал комментарии что поправить и улучшить

в целом после правок готов принять работу

2024-12-02 16:48 UTC, dirtymew commented on Dockerfile
> +RUN go mod tidy
go mod download лучше

2024-12-02 16:48 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./cmd/main.go
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 лучше в ENV

2024-12-02 16:48 UTC, dirtymew commented on Dockerfile
> +FROM ubuntu:latest
можно взять образ полегче - что-то вроде alpine

2024-12-02 16:48 UTC, dirtymew commented on README.md
> +# Итоговый проект ЯндексПрактикума курс Go-Basic ![Go](https://img.shields.io/badge/go-%2300ADD8.svg?style=for-the-badge&logo=go&logoColor=white)
отлично что дописал докумнетацию

2024-12-02 16:48 UTC, dirtymew commented on cmd/main.go
> +	"github.com/joho/godotenv"
что-то не так с импортами - используй go imports для группировки

2024-12-02 16:48 UTC, dirtymew commented on internal/db/db.go
> +        id INTEGER PRIMARY KEY AUTOINCREMENT,
по заданию требовалось ограничить длинну некоторых полей

2024-12-02 16:48 UTC, dirtymew commented on internal/db/db.go
> +		fmt.Println("AAAAAAAAAAAA")
это что-то явно лишнее

2024-12-02 16:48 UTC, dirtymew commented on internal/db/db.go
> +		fmt.Println("dddddddddddddddddd")
для логирование уже используешь лог

а если дебага то освой дебагер - не делай это принтами

2024-12-02 16:48 UTC, dirtymew commented on internal/db/db.go
> +			ORDER BY date ASC LIMIT 50`,
лимит в константу вынести

2024-12-02 16:48 UTC, dirtymew commented on internal/db/db.go
> +		fmt.Println("eeeeeeeeeeeeeeeeeee")
все это нужно убрать

2024-12-02 16:48 UTC, dirtymew commented on tests/settings.go
> +var Search = false
нужно включить эту опцию раз реализовал поиск

2024-12-02 16:48 UTC, dirtymew commented on internal/webserver/webserver.go
> +	startDate, err := time.Parse("20060102", date)
20060102 в константу и везде использовать

2024-12-02 16:48 UTC, dirtymew commented on internal/webserver/webserver.go
> +		w.Write(errResp)
ошибки из w.Write не обрабатыешь ...

2024-12-02 16:48 UTC, dirtymew commented on internal/webserver/webserver.go
> +func InitWebServer(conf models.ServiceConfig) error {
Рекомендации по рефакторингу(не обязательно)

- вся логика организована в хендлерах - проект не маленький и они уже перегружены проверками и запросами - стоит провести рефакторинг
- проверки лучше вынести в методы/функции и другие пакеты
- по структуре проекта https://github.com/golang-standards/project-layout
- по архитектуре - https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10 и в задании про посылки можно подсмотреть как организованы service и storage

2024-12-02 16:48 UTC, dirtymew commented on internal/db/db.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-12-02 16:48 UTC, dirtymew commented on cmd/main.go
> +func main() {
при запуске 
<img width="1177" alt="image" src="https://github.com/user-attachments/assets/1f8edf93-265c-4319-bba3-33947ad16668">
по идее все что нужно приложения должно создавать само

2024-12-02 16:48 UTC, dirtymew commented on cmd/main.go
> +	log.Println("Старт приложения")
еще стоило порт напечатать

2024-12-02 16:48 UTC, dirtymew commented on cmd/main.go
> +func main() {
нужно папку создавать dbdata

2024-12-03 20:11 UTC, NotUrBruddah commented on Dockerfile
> +RUN go mod tidy
done

2024-12-03 20:12 UTC, NotUrBruddah commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./cmd/main.go
done

2024-12-03 20:12 UTC, NotUrBruddah commented on Dockerfile
> +FROM ubuntu:latest
done

2024-12-03 20:12 UTC, NotUrBruddah commented on cmd/main.go
> +	"github.com/joho/godotenv"
done
`sudo apt install golang-golang-x-tools`

2024-12-03 20:12 UTC, NotUrBruddah commented on cmd/main.go
> +	"github.com/joho/godotenv"
после этого применяем из каталога проекта
goimports -w cmd/main.go
goimports -w internal/db/db.go
goimports -w internal/utils/utils.go
goimports -w internal/webserver/webserver.go

2024-12-03 20:31 UTC, NotUrBruddah commented on internal/db/db.go
> +        id INTEGER PRIMARY KEY AUTOINCREMENT,
Да, Вы правы, совсем забыл про это 
Изменил формат полей и выставил на них ограничения

2024-12-03 20:31 UTC, NotUrBruddah commented on README.md
> +# Итоговый проект ЯндексПрактикума курс Go-Basic ![Go](https://img.shields.io/badge/go-%2300ADD8.svg?style=for-the-badge&logo=go&logoColor=white)
спасибо

2024-12-03 20:31 UTC, NotUrBruddah commented on internal/db/db.go
> +		fmt.Println("AAAAAAAAAAAA")
убрал мусор

2024-12-03 20:32 UTC, NotUrBruddah commented on internal/db/db.go
> +		fmt.Println("dddddddddddddddddd")
убрал мусор, долго отлаживал, убрал мусор

2024-12-03 20:32 UTC, NotUrBruddah commented on internal/db/db.go
> +			ORDER BY date ASC LIMIT 50`,
done

2024-12-03 20:32 UTC, NotUrBruddah commented on internal/db/db.go
> +		fmt.Println("eeeeeeeeeeeeeeeeeee")
done

2024-12-03 20:33 UTC, NotUrBruddah commented on tests/settings.go
> +var Search = false
done

2024-12-03 20:33 UTC, NotUrBruddah commented on internal/webserver/webserver.go
> +	startDate, err := time.Parse("20060102", date)
done

2024-12-03 20:50 UTC, NotUrBruddah commented on internal/webserver/webserver.go
> +		w.Write(errResp)
поправил

2024-12-03 20:50 UTC, NotUrBruddah commented on internal/webserver/webserver.go
> +func InitWebServer(conf models.ServiceConfig) error {
Взял на дополнительное изучение

2024-12-03 20:58 UTC, NotUrBruddah commented on internal/db/db.go
> +
done

2024-12-03 21:22 UTC, NotUrBruddah commented on cmd/main.go
> +	log.Println("Старт приложения")
done

2024-12-04 05:30 UTC, dirtymew approved these changes
Привет Андрей

работу принимаю

Поздравляю и желаю удачи

2024-12-04 08:34 UTC, merged